server:
  port: 8181

logging:
  level:
    root: info
    com.hazelcast: info

hazelcast:
  group:
    name: your-hazelcast-group-name
  metrics.enabled: true
  integrity-checker:
    enabled: true
  diagnostics.enabled: true
  network:
    join:
      multicast:
        enabled: false
      kubernetes:
        enabled: true
        service-port: 5701

